# left-side user profile
avatar: https://avatars.githubusercontent.com/u/2194861?s=400&u=7ac333e4b5c5f102bbc17dcc33ee4dc0d429e9aa&v=4 # by default https://octodex.github.com/images/baracktocat.jpg
location: Nanjing
email: bejea27#gmail.com
social:
  github: https://github.com/aloncn
  weibo: https://weibo.com/u/1394600500
  linkedin:

# navbar menu
menu:
 archives: true
 tags: true
 categories: true

rss_dir: atom.xml

# widget
ga: # google analytics tracking code UA-XXXXXXX-X
baidutongji: # baidutongji tracking code
duoshuo: # duoshuo username
gcs: # google custom search code

# flagcounter
flagcounter_href: # https://info.flagcounter.com/xxxx
flagcounter_img_src: # https://s01.flagcounter.com/xxxx

# article_edit 在文章页显示跳转到编辑页
article_edit:
  enable: false #是否启用
  prefix: https://github.com/xxx/xxx/edit/master/source/  #编辑页前缀
